In [10]:
import numpy as np


let matrix be A

question 5 (i)

In [12]:
A=np.array ([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
A

array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])

In [13]:
TA=np.transpose(A)
TA

array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])

ii

In [15]:
determinant=np.linalg.det(A)
determinant

np.float64(0.2299999999999999)

iii

In [17]:
decomposition=np.linalg.cholesky(A)
decomposition


array([[1.        , 0.        , 0.        ],
       [0.2       , 0.9797959 , 0.        ],
       [0.5       , 0.71443451, 0.48947251]])

iv

In [22]:
A=np.array
A

array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])

question 6

i

In [60]:
from numpy import random
Y=random.normal(loc=5,size=(1000))
Y

array([4.0662706 , 4.9194443 , 5.18879247, 5.23849524, 4.40189969,
       5.32482651, 3.84853728, 4.51688589, 4.66633028, 7.22704903,
       5.30772158, 6.77698737, 4.1625327 , 5.77569567, 5.45711146,
       4.91143122, 4.94232342, 5.89312692, 3.98374699, 5.82785946,
       7.26828706, 6.26261324, 5.79379802, 5.32235857, 4.69541   ,
       4.57950516, 5.31288848, 4.40581202, 3.30138579, 5.39178658,
       4.6918049 , 4.6934373 , 5.18825339, 4.29518004, 5.4877874 ,
       4.51318426, 4.44506524, 4.47385217, 5.73732343, 4.37646738,
       5.90698148, 4.78820431, 4.41694983, 4.42094551, 4.96784684,
       6.63316732, 3.29578479, 5.10326377, 3.77641653, 4.85121108,
       3.70698418, 4.89258974, 2.79914742, 4.40072415, 5.73819184,
       7.37981411, 2.39469655, 4.55687192, 6.39987312, 6.03836446,
       4.40913166, 4.95720665, 5.17102255, 4.5649534 , 3.93565842,
       7.09544187, 4.61624636, 4.38461512, 5.49839542, 4.81574972,
       5.82404071, 5.09356124, 4.99961999, 5.33346908, 6.76063

ii

iii

In [64]:
import matplotlib.pyplot as plt

In [65]:
import seaborn as sns

In [66]:
plt.hist(average ,random sample)
plt.title("Poisson Distribution")
plt.xlebel("average")
plt.ylebel("random samples")
plt.show()

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1508311773.py, line 1)